### ISSUE TITLE
Project Setup Link

### ISSUE THREAD

**Issue by cancelei** [cancelei/Space-Travelers-Hub#21]
https://github.com/cancelei/Space-Travelers-Hub/projects/1

We set up for 3 people.
- Glauber Bannwart
- Ricardo Martinez
- Rodolfo Carrillo

**Comment by julie-ify** [comment]
## Hi @cancelei and @bohaz,

Good job so far!

## Highlights!
- Descriptive Issue✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
- [ ] You should have 17 tasks in the Kanban board, but you have only 13. You are missing these four tasks. Kindly add them.

  ![image](https://github.com/cancelei/Space-Travelers-Hub/assets/81468675/3f5449d5-4c77-4acc-b010-e5d0f20a2a52)

- [ ] Kindly ensure you assign your tasks. None of them are assigned at the moment.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by cancelei** [comment]
Thank you. 

For the new Reviewer: We corrected that issue with the total card number and assigned ourselves to the corresponding cards.

**Comment by V-Blaze** [comment]
Hi @cancelei, @bohaz  

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Kanban board setup correctly💯
-  All cards are assigned to correct student👍🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
